#
# FeatherClans
#
settings:
  use_economy: false
  economy:
    creation_price: 100.0
    invite_price: 100.0
    set_home_price: 100.0
  use_clean_up: false
  clean_up:
    archive_days: 30
    delete_days: 45
  clan:
    invite_timeout: 30
    teleport_delay_seconds: 5
    tag_size: 5
    max_members: 20
  use_mysql: false
  mysql:
    username: ''
    host: localhost
    port: 3306
    enable: false
    password: ''
    database: ''
  deny_tags:
    - "admin"
    - "mods"
    - "mod"
    - "donor"
    - "admln"
    - "adnin"
    - "admim"
    - "adnim"
