#
# FeatherClans
#
#
# Permission nodes:
#
# feather.clans.accept
# feather.clans.chat
# feather.clans.confer
# feather.clans.create
# feather.clans.decline
# feather.clans.disband
# feather.clans.friendlyfire
# feather.clans.home
# feather.clans.home.others
# feather.clans.invite
# feather.clans.kick
# feather.clans.list
# feather.clans.manage
# feather.clans.resign
# feather.clans.roster
# feather.clans.sethome
# feather.clans.banner

settings:
  economy:
    enabled: true
    creation_price: 25000.0
    invite_price: 100.0
    set_home_price: 1000.0
  clean_up:
    enabled: false
    archive_days: 30
    delete_days: 45
  clan:
    invite_timeout: 30
    teleport_delay_seconds: 4
    min_tag_size: 3
    max_tag_size: 5
    max_members: 30
    auto_kick_inactive_days: 64
  mysql:
    enabled: true
    username: 'feather_clans'
    # set for pterodactyl usage
    host: '172.17.0.1'
    port: 3306
    password: ''
    database: 'clans'
  deny_tags:
    - "admin"
    - "zerek"
    - "mwcks"
    - "mawks"
    - "mawck"
    - "mods"
    - "mod"
    - "donor"
    - "admln"
    - "adnin"
    - "admim"
    - "adnim"
  page-formats:
    lines-per-page: 8
  pvp-score:
    relevant-days: 64
    calculation-explained: "1 point for every clan player you've killed more than they've killed you.
                        <br>Only the kills within the last <days> days count."
  xp-score:
    relevant-days: 64
    calculation-explained: "XP score is calculated ...
                        <br>... "