#
# FeatherClans
#
#
# Permission nodes:
#
# feather.clans.accept
# feather.clans.chat
# feather.clans.confer
# feather.clans.create
# feather.clans.decline
# feather.clans.disband
# feather.clans.friendlyfire
# feather.clans.home
# feather.clans.home.others
# feather.clans.invite
# feather.clans.kick
# feather.clans.list
# feather.clans.manage
# feather.clans.resign
# feather.clans.roster
# feather.clans.sethome
# feather.clans.banner

settings:
  economy:
    enabled: true
    creation_price: 100000.0
    invite_price: 100.0
    set_home_price: 1000.0
    set_armor_price: 5000.0
    set_tag_price: 5000.0
    set_banner_price: 25000.0
  clean_up:
    enabled: false
    archive_days: 30
    delete_days: 45
  clan:
    # The amount of days a player who doesn't log in would be considered inactive.
    inactive_days_threshold: 4
    # The amount of active members a clan must have to be considered itself active.
    active_members_requirement: 4
    invite_timeout: 30
    teleport_delay_seconds: 4
    min_tag_size: 3
    max_tag_size: 5
    max_members: 30
  display:
    location: [0, 0, 0]
    facing: NORTH
    count: 10
    sign_type: OAK
  mysql:
    enabled: true
    username: ''
    # set for pterodactyl usage
    host: ''
    port: 3306
    password: ''
    database: ''
  deny_tags:
    - "admin"
    - "zerek"
    - "mwcks"
    - "mawks"
    - "mawck"
    - "mods"
    - "mod"
    - "donor"
    - "admln"
    - "adnin"
    - "admim"
    - "adnim"
page-formats:
  lines-per-page: 8