name: FeatherClans
version: ${project.version}
main: com.wasted_ticks.featherclans.FeatherClans
api-version: 1.18
authors: [ Wasted_Ticks ]
softdepend:
  - Vault
  - PlaceholderAPI
commands:
  clan:
    description: gives access to clan related commands
    usage: /clan