name: FeatherClans
version: ${project.version}
main: com.wasted_ticks.featherclans.FeatherClans
api-version: 1.19
authors: [ Zerek, Wasted_Ticks ]
softdepend:
  - Vault
  - PlaceholderAPI
  - LuckPerms
commands:
  clan:
    description: gives access to clan related commands
    usage: /clan