name: FeatherClans
version: ${project.version}
main: com.wasted_ticks.featherclans.FeatherClans
api-version: 1.21
authors:
  - Wasted_Ticks
  - Zerek
softdepend:
  - Vault
  - PlaceholderAPI
commands:
  clan:
    description: gives access to clan related commands
    usage: /clan